
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AdminUsers': typeof import("../components/admin/Users.vue")['default']
    'AdminIconsEdit': typeof import("../components/admin/icons/Edit.vue")['default']
    'AdminIconsLogout': typeof import("../components/admin/icons/Logout.vue")['default']
    'AdminIconsShopping': typeof import("../components/admin/icons/Shopping.vue")['default']
    'AdminIconsTrash': typeof import("../components/admin/icons/Trash.vue")['default']
    'AdminIconsEditProfile': typeof import("../components/admin/icons/editProfile.vue")['default']
    'UserCoundownOtp': typeof import("../components/user/CoundownOtp.vue")['default']
    'UserDiscountCoupon': typeof import("../components/user/DiscountCoupon.vue")['default']
    'UserMenu': typeof import("../components/user/Menu.vue")['default']
    'UserMenuDesktop': typeof import("../components/user/MenuDesktop.vue")['default']
    'UserNavbar': typeof import("../components/user/Navbar.vue")['default']
    'UserPacket': typeof import("../components/user/Packet.vue")['default']
    'UserProductSale': typeof import("../components/user/ProductSale.vue")['default']
    'UserPromotion': typeof import("../components/user/Promotion.vue")['default']
    'UserPromotionSlide': typeof import("../components/user/PromotionSlide.vue")['default']
    'UserRecommendedShops': typeof import("../components/user/RecommendedShops.vue")['default']
    'UserSearch': typeof import("../components/user/Search.vue")['default']
    'UserShopNear': typeof import("../components/user/ShopNear.vue")['default']
    'UserStoresNear': typeof import("../components/user/StoresNear.vue")['default']
    'UserFoodCategories': typeof import("../components/user/foodCategories.vue")['default']
    'UserIconsApple': typeof import("../components/user/icons/Apple.vue")['default']
    'UserIconsEmail': typeof import("../components/user/icons/Email.vue")['default']
    'UserIconsFacebook': typeof import("../components/user/icons/Facebook.vue")['default']
    'UserIconsGoogle': typeof import("../components/user/icons/Google.vue")['default']
    'UserIconsLine': typeof import("../components/user/icons/Line.vue")['default']
    'UserIconsProfileChat': typeof import("../components/user/icons/Profile/Chat.vue")['default']
    'UserIconsProfileCoupon': typeof import("../components/user/icons/Profile/Coupon.vue")['default']
    'UserIconsProfileHelp': typeof import("../components/user/icons/Profile/Help.vue")['default']
    'UserIconsProfileLocation': typeof import("../components/user/icons/Profile/Location.vue")['default']
    'UserIconsProfilePayment': typeof import("../components/user/icons/Profile/Payment.vue")['default']
    'UserIconsProfileRight': typeof import("../components/user/icons/Profile/Right.vue")['default']
    'UserIconsProfileSecurity': typeof import("../components/user/icons/Profile/Security.vue")['default']
    'UserIconsProfileInviteFriend': typeof import("../components/user/icons/Profile/inviteFriend.vue")['default']
    'UserIconsUser': typeof import("../components/user/icons/User.vue")['default']
    'UserIconsCheck': typeof import("../components/user/icons/check.vue")['default']
    'UserIconsClock': typeof import("../components/user/icons/clock.vue")['default']
    'UserIconsCoupon': typeof import("../components/user/icons/coupon.vue")['default']
    'UserIconsCouponlight': typeof import("../components/user/icons/couponlight.vue")['default']
    'UserIconsIconSaleInput': typeof import("../components/user/icons/iconSaleInput.vue")['default']
    'UserIconsUpcost': typeof import("../components/user/icons/upcost.vue")['default']
    'UserIconsUserLogin': typeof import("../components/user/icons/userLogin.vue")['default']
    'UserOtpInput': typeof import("../components/user/otpInput.vue")['default']
    'UserShopCategories': typeof import("../components/user/shopCategories.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAdminUsers': typeof import("../components/admin/Users.vue")['default']
    'LazyAdminIconsEdit': typeof import("../components/admin/icons/Edit.vue")['default']
    'LazyAdminIconsLogout': typeof import("../components/admin/icons/Logout.vue")['default']
    'LazyAdminIconsShopping': typeof import("../components/admin/icons/Shopping.vue")['default']
    'LazyAdminIconsTrash': typeof import("../components/admin/icons/Trash.vue")['default']
    'LazyAdminIconsEditProfile': typeof import("../components/admin/icons/editProfile.vue")['default']
    'LazyUserCoundownOtp': typeof import("../components/user/CoundownOtp.vue")['default']
    'LazyUserDiscountCoupon': typeof import("../components/user/DiscountCoupon.vue")['default']
    'LazyUserMenu': typeof import("../components/user/Menu.vue")['default']
    'LazyUserMenuDesktop': typeof import("../components/user/MenuDesktop.vue")['default']
    'LazyUserNavbar': typeof import("../components/user/Navbar.vue")['default']
    'LazyUserPacket': typeof import("../components/user/Packet.vue")['default']
    'LazyUserProductSale': typeof import("../components/user/ProductSale.vue")['default']
    'LazyUserPromotion': typeof import("../components/user/Promotion.vue")['default']
    'LazyUserPromotionSlide': typeof import("../components/user/PromotionSlide.vue")['default']
    'LazyUserRecommendedShops': typeof import("../components/user/RecommendedShops.vue")['default']
    'LazyUserSearch': typeof import("../components/user/Search.vue")['default']
    'LazyUserShopNear': typeof import("../components/user/ShopNear.vue")['default']
    'LazyUserStoresNear': typeof import("../components/user/StoresNear.vue")['default']
    'LazyUserFoodCategories': typeof import("../components/user/foodCategories.vue")['default']
    'LazyUserIconsApple': typeof import("../components/user/icons/Apple.vue")['default']
    'LazyUserIconsEmail': typeof import("../components/user/icons/Email.vue")['default']
    'LazyUserIconsFacebook': typeof import("../components/user/icons/Facebook.vue")['default']
    'LazyUserIconsGoogle': typeof import("../components/user/icons/Google.vue")['default']
    'LazyUserIconsLine': typeof import("../components/user/icons/Line.vue")['default']
    'LazyUserIconsProfileChat': typeof import("../components/user/icons/Profile/Chat.vue")['default']
    'LazyUserIconsProfileCoupon': typeof import("../components/user/icons/Profile/Coupon.vue")['default']
    'LazyUserIconsProfileHelp': typeof import("../components/user/icons/Profile/Help.vue")['default']
    'LazyUserIconsProfileLocation': typeof import("../components/user/icons/Profile/Location.vue")['default']
    'LazyUserIconsProfilePayment': typeof import("../components/user/icons/Profile/Payment.vue")['default']
    'LazyUserIconsProfileRight': typeof import("../components/user/icons/Profile/Right.vue")['default']
    'LazyUserIconsProfileSecurity': typeof import("../components/user/icons/Profile/Security.vue")['default']
    'LazyUserIconsProfileInviteFriend': typeof import("../components/user/icons/Profile/inviteFriend.vue")['default']
    'LazyUserIconsUser': typeof import("../components/user/icons/User.vue")['default']
    'LazyUserIconsCheck': typeof import("../components/user/icons/check.vue")['default']
    'LazyUserIconsClock': typeof import("../components/user/icons/clock.vue")['default']
    'LazyUserIconsCoupon': typeof import("../components/user/icons/coupon.vue")['default']
    'LazyUserIconsCouponlight': typeof import("../components/user/icons/couponlight.vue")['default']
    'LazyUserIconsIconSaleInput': typeof import("../components/user/icons/iconSaleInput.vue")['default']
    'LazyUserIconsUpcost': typeof import("../components/user/icons/upcost.vue")['default']
    'LazyUserIconsUserLogin': typeof import("../components/user/icons/userLogin.vue")['default']
    'LazyUserOtpInput': typeof import("../components/user/otpInput.vue")['default']
    'LazyUserShopCategories': typeof import("../components/user/shopCategories.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AdminUsers: typeof import("../components/admin/Users.vue")['default']
export const AdminIconsEdit: typeof import("../components/admin/icons/Edit.vue")['default']
export const AdminIconsLogout: typeof import("../components/admin/icons/Logout.vue")['default']
export const AdminIconsShopping: typeof import("../components/admin/icons/Shopping.vue")['default']
export const AdminIconsTrash: typeof import("../components/admin/icons/Trash.vue")['default']
export const AdminIconsEditProfile: typeof import("../components/admin/icons/editProfile.vue")['default']
export const UserCoundownOtp: typeof import("../components/user/CoundownOtp.vue")['default']
export const UserDiscountCoupon: typeof import("../components/user/DiscountCoupon.vue")['default']
export const UserMenu: typeof import("../components/user/Menu.vue")['default']
export const UserMenuDesktop: typeof import("../components/user/MenuDesktop.vue")['default']
export const UserNavbar: typeof import("../components/user/Navbar.vue")['default']
export const UserPacket: typeof import("../components/user/Packet.vue")['default']
export const UserProductSale: typeof import("../components/user/ProductSale.vue")['default']
export const UserPromotion: typeof import("../components/user/Promotion.vue")['default']
export const UserPromotionSlide: typeof import("../components/user/PromotionSlide.vue")['default']
export const UserRecommendedShops: typeof import("../components/user/RecommendedShops.vue")['default']
export const UserSearch: typeof import("../components/user/Search.vue")['default']
export const UserShopNear: typeof import("../components/user/ShopNear.vue")['default']
export const UserStoresNear: typeof import("../components/user/StoresNear.vue")['default']
export const UserFoodCategories: typeof import("../components/user/foodCategories.vue")['default']
export const UserIconsApple: typeof import("../components/user/icons/Apple.vue")['default']
export const UserIconsEmail: typeof import("../components/user/icons/Email.vue")['default']
export const UserIconsFacebook: typeof import("../components/user/icons/Facebook.vue")['default']
export const UserIconsGoogle: typeof import("../components/user/icons/Google.vue")['default']
export const UserIconsLine: typeof import("../components/user/icons/Line.vue")['default']
export const UserIconsProfileChat: typeof import("../components/user/icons/Profile/Chat.vue")['default']
export const UserIconsProfileCoupon: typeof import("../components/user/icons/Profile/Coupon.vue")['default']
export const UserIconsProfileHelp: typeof import("../components/user/icons/Profile/Help.vue")['default']
export const UserIconsProfileLocation: typeof import("../components/user/icons/Profile/Location.vue")['default']
export const UserIconsProfilePayment: typeof import("../components/user/icons/Profile/Payment.vue")['default']
export const UserIconsProfileRight: typeof import("../components/user/icons/Profile/Right.vue")['default']
export const UserIconsProfileSecurity: typeof import("../components/user/icons/Profile/Security.vue")['default']
export const UserIconsProfileInviteFriend: typeof import("../components/user/icons/Profile/inviteFriend.vue")['default']
export const UserIconsUser: typeof import("../components/user/icons/User.vue")['default']
export const UserIconsCheck: typeof import("../components/user/icons/check.vue")['default']
export const UserIconsClock: typeof import("../components/user/icons/clock.vue")['default']
export const UserIconsCoupon: typeof import("../components/user/icons/coupon.vue")['default']
export const UserIconsCouponlight: typeof import("../components/user/icons/couponlight.vue")['default']
export const UserIconsIconSaleInput: typeof import("../components/user/icons/iconSaleInput.vue")['default']
export const UserIconsUpcost: typeof import("../components/user/icons/upcost.vue")['default']
export const UserIconsUserLogin: typeof import("../components/user/icons/userLogin.vue")['default']
export const UserOtpInput: typeof import("../components/user/otpInput.vue")['default']
export const UserShopCategories: typeof import("../components/user/shopCategories.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAdminUsers: typeof import("../components/admin/Users.vue")['default']
export const LazyAdminIconsEdit: typeof import("../components/admin/icons/Edit.vue")['default']
export const LazyAdminIconsLogout: typeof import("../components/admin/icons/Logout.vue")['default']
export const LazyAdminIconsShopping: typeof import("../components/admin/icons/Shopping.vue")['default']
export const LazyAdminIconsTrash: typeof import("../components/admin/icons/Trash.vue")['default']
export const LazyAdminIconsEditProfile: typeof import("../components/admin/icons/editProfile.vue")['default']
export const LazyUserCoundownOtp: typeof import("../components/user/CoundownOtp.vue")['default']
export const LazyUserDiscountCoupon: typeof import("../components/user/DiscountCoupon.vue")['default']
export const LazyUserMenu: typeof import("../components/user/Menu.vue")['default']
export const LazyUserMenuDesktop: typeof import("../components/user/MenuDesktop.vue")['default']
export const LazyUserNavbar: typeof import("../components/user/Navbar.vue")['default']
export const LazyUserPacket: typeof import("../components/user/Packet.vue")['default']
export const LazyUserProductSale: typeof import("../components/user/ProductSale.vue")['default']
export const LazyUserPromotion: typeof import("../components/user/Promotion.vue")['default']
export const LazyUserPromotionSlide: typeof import("../components/user/PromotionSlide.vue")['default']
export const LazyUserRecommendedShops: typeof import("../components/user/RecommendedShops.vue")['default']
export const LazyUserSearch: typeof import("../components/user/Search.vue")['default']
export const LazyUserShopNear: typeof import("../components/user/ShopNear.vue")['default']
export const LazyUserStoresNear: typeof import("../components/user/StoresNear.vue")['default']
export const LazyUserFoodCategories: typeof import("../components/user/foodCategories.vue")['default']
export const LazyUserIconsApple: typeof import("../components/user/icons/Apple.vue")['default']
export const LazyUserIconsEmail: typeof import("../components/user/icons/Email.vue")['default']
export const LazyUserIconsFacebook: typeof import("../components/user/icons/Facebook.vue")['default']
export const LazyUserIconsGoogle: typeof import("../components/user/icons/Google.vue")['default']
export const LazyUserIconsLine: typeof import("../components/user/icons/Line.vue")['default']
export const LazyUserIconsProfileChat: typeof import("../components/user/icons/Profile/Chat.vue")['default']
export const LazyUserIconsProfileCoupon: typeof import("../components/user/icons/Profile/Coupon.vue")['default']
export const LazyUserIconsProfileHelp: typeof import("../components/user/icons/Profile/Help.vue")['default']
export const LazyUserIconsProfileLocation: typeof import("../components/user/icons/Profile/Location.vue")['default']
export const LazyUserIconsProfilePayment: typeof import("../components/user/icons/Profile/Payment.vue")['default']
export const LazyUserIconsProfileRight: typeof import("../components/user/icons/Profile/Right.vue")['default']
export const LazyUserIconsProfileSecurity: typeof import("../components/user/icons/Profile/Security.vue")['default']
export const LazyUserIconsProfileInviteFriend: typeof import("../components/user/icons/Profile/inviteFriend.vue")['default']
export const LazyUserIconsUser: typeof import("../components/user/icons/User.vue")['default']
export const LazyUserIconsCheck: typeof import("../components/user/icons/check.vue")['default']
export const LazyUserIconsClock: typeof import("../components/user/icons/clock.vue")['default']
export const LazyUserIconsCoupon: typeof import("../components/user/icons/coupon.vue")['default']
export const LazyUserIconsCouponlight: typeof import("../components/user/icons/couponlight.vue")['default']
export const LazyUserIconsIconSaleInput: typeof import("../components/user/icons/iconSaleInput.vue")['default']
export const LazyUserIconsUpcost: typeof import("../components/user/icons/upcost.vue")['default']
export const LazyUserIconsUserLogin: typeof import("../components/user/icons/userLogin.vue")['default']
export const LazyUserOtpInput: typeof import("../components/user/otpInput.vue")['default']
export const LazyUserShopCategories: typeof import("../components/user/shopCategories.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
