// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/19/2024, 1:11:51 PM
const configMerger = require("/Users/sirawitkumlungsri/Documents/GitHub/homefood-webapp/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/sirawitkumlungsri/Documents/GitHub/homefood-webapp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood-webapp/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood-webapp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood-webapp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood-webapp/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood-webapp/plugins/**/*.{js,ts,mjs}","/Users/sirawitkumlungsri/Documents/GitHub/homefood-webapp/composables/**/*.{js,ts,mjs}","/Users/sirawitkumlungsri/Documents/GitHub/homefood-webapp/utils/**/*.{js,ts,mjs}","/Users/sirawitkumlungsri/Documents/GitHub/homefood-webapp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood-webapp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sirawitkumlungsri/Documents/GitHub/homefood-webapp/app.config.{js,ts,mjs}"] } }));

module.exports = config
